{% set name = "fts-rest" %}
{% set version = "3.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/fts/fts-rest/-/archive/v{{ version }}/fts-rest-v{{ version }}.tar.gz
  sha256: f008f7e57ea0ed22e8ac292482069fb271ef3f747abbc58709f4da4cf956060f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - pycurl
    - m2crypto >=0.16
    - requests
    - sqlalchemy
    - setuptools

test:
  imports:
    - fts3
    - fts3.cli
    - fts3.model
    - fts3.rest
    - fts3.rest.client
    - fts3.rest.client.easy

about:
  home: https://fts.web.cern.ch/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: File Transfer Service REST API
  doc_url: http://fts3-docs.web.cern.ch/fts3-docs/fts-rest/docs/easy/index.html
  dev_url: https://gitlab.cern.ch/fts/fts-rest/

extra:
  recipe-maintainers:
    - chrisburr
