travis:
  secure:
    BINSTAR_TOKEN: ExDqUBZo6OsOYChWU85k7I4+zLUQOrbiUMIJbVDmcxL4vGTcO0WDJmFgM7CAzyXKbCYP2o1UW0i41tnj+lasXTIHy568wqy/oBZobOZJCmWCyUq1Ef2ghq204ZfDsGPfSU+vwzqRgl3PtmUmhsfkk0PtgoMeSEhvwCyUmRjQZkVXt/M8YQD36CuF3I5m19rO8ikaaHEfRUV2/qTYLg06LQXhssrPwWssQAxrkmhBvSYDiKfqmeaLOut1ebWTwyD2PsymyP+JYIIL76TEhzT1hVENTuwOHNnAKS2ADXrzrvF5Pq5SQLrFuX5fdRQnTcGU6PQ/bsnvsosL00My2Ukh5rPFNnYD9oXPz/j0m6LDWdTYabUlyRKrj1BFnahU1RbmuZg2Hxz88oIvfUwKt63RgCSwbUrjgNlsveSlowRbaJTZrmxmTP37iDFDHpcZN2eyuWbvkSF8otQ9XLapihCPe6EZBsFm3rlezO9ceLrMT59u1FftDZ4I3emcBrRxF5Md+vWUCVWv86/ZmFhGq/ZR/QxZaLAOy6C47EcUbEsn7ZSZBlHq+dZFQ5wxAwnrD7hSh9RmRRBonfARraXFSvYZYQeSzieOHtUjn2rimajhwjSv1fS5nVmbZY5gjvoWyN/gahckbhxJoyZ4a8xiIhFtv7tKSZlFbF+t0GSHhv2hVT0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
